### PR TITLE
Update dependencies to community versions.

### PR DESCRIPTION
**Pull request by dannys42**

### CODE REVIEW

**Review by fouadhatem — APPROVED** [review]

**Review by futurejones — CHANGES_REQUESTED** [review]
The release versions you are referencing don't exist yet.
All the individual repos referenced need to have the new `200` releases before you can reference them in the package files.

**Comment by dannys42** [comment]
@futurejones I did create tags, which I think is all that SPM cares for (note that CI did pass successfully).  It's a good point that I hadn't checked GitHub releases, though.  Is there really any reason to support them?  I see that OpenSSL doesn't even have releases for many of the prior tags.  Maybe just for major or minor releases, but not patch releases?

**Comment by futurejones** [comment]
I missed the tag which should be ok but I thought the purpose of the update was to reflect the change to the Kitura Organization?
Shouldn't we be doing a proper release with an explanation as to what the release is for?

**Comment by dannys42** [comment]
> I missed the tag which should be ok but I thought the purpose of the update was to reflect the change to the Kitura Organization?
> Shouldn't we be doing a proper release with an explanation as to what the release is for?

Yeah, that's a good point.  I'll start doing that.

**Pull request merged**
